services:
  postgres:
    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - archive_mode=on
      - -c
      - archive_timeout=60s
      - -c
      - archive_command=test ! -f /var/lib/postgresql/wal-archive/%f && cp %p /var/lib/postgresql/wal-archive/%f
    volumes:
      - nhienin3d-postgres-wal-archive:/var/lib/postgresql/wal-archive

volumes:
  nhienin3d-postgres-wal-archive:
