import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
const read = p => readFileSync(p, "utf8");

test("v3.29.0 dong bo RMA partial refund COGS va gross margin", () => {
  const pkg = JSON.parse(read("package.json"));
  const schema = read("apps/api/prisma/schema.prisma");
  const migration = read("apps/api/prisma/migrations/202609080001_v329_returns_partial_refund_margin/migration.sql");
  const service = read("apps/api/src/quan-tri/quan-tri.service.ts");
  const controller = read("apps/api/src/quan-tri/quan-tri.controller.ts");
  const runtime = read("scripts/e2e-runtime-v3290.ps1");
  assert.equal(read("VERSION").trim(), "3.29.0");
  assert.equal(pkg.version, "3.29.0");
  assert.equal(JSON.parse(read("apps/api/package.json")).version, "3.29.0");
  assert.equal(JSON.parse(read("apps/web/package.json")).version, "3.29.0");
  assert.equal(pkg.scripts.verify, "npm run verify:v329");
  assert.equal(pkg.scripts["verify:full"], "npm run verify:full:v329");
  assert.equal(pkg.scripts["e2e:browser"], "node scripts/e2e-browser-v3290.mjs");
  assert.equal(existsSync("scripts/verify-v3290.ps1"), true);
  assert.equal(existsSync("scripts/e2e-runtime-v3290.ps1"), true);
  assert.equal(existsSync("apps/api/prisma/migrations/202609080001_v329_returns_partial_refund_margin/migration.sql"), true);
  assert.equal(readdirSync("apps/api/prisma/migrations", { withFileTypes: true }).filter(x => x.isDirectory()).length, 25);
  assert.match(schema, /model YeuCauDoiTra\b/);
  assert.match(schema, /model ChiTietDoiTra\b/);
  assert.match(schema, /model HoanTienDonHang\b/);
  assert.match(schema, /gia_von_snapshot\s+Decimal\?/);
  assert.match(migration, /CREATE TYPE "TrangThaiYeuCauDoiTra"/);
  assert.match(migration, /CREATE TABLE "hoan_tien_don_hang"/);
  assert.match(controller, /@Get\("doi-tra"\)/);
  assert.match(controller, /@Post\("doi-tra\/:id\/hoan-tien"\)/);
  assert.match(controller, /@Get\("bao-cao\/loi-nhuan\/excel"\)/);
  assert.match(service, /partial_refund_ledger: true/);
  assert.match(service, /gross_margin_dashboard: true/);
  assert.match(service, /sale_time_cost_snapshot: true/);
  assert.match(service, /refund_gateway_automation: false/);
  assert.match(service, /yeu_cau: \{ is: \{ trang_thai: \{ not: TrangThaiYeuCauDoiTra\.HUY \} \} \}/);
  assert.match(service, /database_migration_count: 25/);
  assert.match(runtime, /202609080001_v329_returns_partial_refund_margin/);
  assert.match(runtime, /partial_refund_ledger/);
  assert.match(runtime, /SALE_TIME_COST_SNAPSHOT_WITH_MIGRATION_BACKFILL/);
});
